### ISSUE TITLE
[Milestone] v1

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/setup-rust-action#2]
- [ ] #1 
- [ ] Work in Container images
- [x] Work in Windows
- [x] Work in macOS
- [x] Work in Ubuntu
- [x] Use defaults! Be zero config
